ALTER PROCEDURE P_RETORNAR_CODIGO
(
	@P_TIPO_CODIGO VARCHAR(4) = '',
	@P_ID_EMPRESA UNIQUEIDENTIFIER  = NULL,
	@P_CODIGO INTEGER = 0 OUTPUT 
)
AS
	BEGIN
		
		DECLARE @V_TIPO_PRODUTO VARCHAR(4) = 'PRDT';
		DECLARE	@V_TIPO_FORNECEDOR VARCHAR(4) = 'FRNC';
		DECLARE	@V_TIPO_CLIENTE VARCHAR(4) = 'CLNT';
		DECLARE	@V_TIPO_ORCAMENTO VARCHAR(4) = 'ORCM';
		DECLARE @V_TIPO_PEDIDO VARCHAR(4) = 'PDDO';

		BEGIN TRAN CODIGO;
					
			IF @P_TIPO_CODIGO = @V_TIPO_PRODUTO
			BEGIN
				
				IF (SELECT COUNT(1) FROM T_EMPRESA_CODIGO WHERE ID_EMPRESA = @P_ID_EMPRESA) > 0
				BEGIN
					UPDATE T_EMPRESA_CODIGO SET COD_PRODUTO = ISNULL(COD_PRODUTO, 0) + 1  WHERE ID_EMPRESA = @P_ID_EMPRESA;
				END
				ELSE
					INSERT INTO T_EMPRESA_CODIGO (COD_PRODUTO, ID_EMPRESA) VALUES (1, @P_ID_EMPRESA);
			END

			IF @P_TIPO_CODIGO = @V_TIPO_FORNECEDOR
			BEGIN
				
				IF (SELECT COUNT(1) FROM T_EMPRESA_CODIGO WHERE ID_EMPRESA = @P_ID_EMPRESA) > 0 							
				BEGIN
					UPDATE T_EMPRESA_CODIGO SET COD_FORNECEDOR = ISNULL(COD_FORNECEDOR, 0) + 1  WHERE ID_EMPRESA = @P_ID_EMPRESA;
				END
				ELSE
					INSERT INTO T_EMPRESA_CODIGO (COD_FORNECEDOR, ID_EMPRESA) VALUES (1, @P_ID_EMPRESA);

			END

			IF @P_TIPO_CODIGO = @V_TIPO_CLIENTE
			BEGIN
				
				IF (SELECT COUNT(1) FROM T_EMPRESA_CODIGO WHERE ID_EMPRESA = @P_ID_EMPRESA) > 0 							
				BEGIN
					UPDATE T_EMPRESA_CODIGO SET COD_CLIENTE = ISNULL(COD_CLIENTE, 0) + 1  WHERE ID_EMPRESA = @P_ID_EMPRESA;
				END
				ELSE
					INSERT INTO T_EMPRESA_CODIGO (COD_CLIENTE, ID_EMPRESA) VALUES (1, @P_ID_EMPRESA);
			END

			IF @P_TIPO_CODIGO = @V_TIPO_ORCAMENTO
			BEGIN

				IF (SELECT COUNT(1) FROM T_EMPRESA_CODIGO WHERE ID_EMPRESA = @P_ID_EMPRESA) > 0 							
				BEGIN
					UPDATE T_EMPRESA_CODIGO SET COD_ORCAMENTO = ISNULL(COD_ORCAMENTO, 0) + 1  WHERE ID_EMPRESA = @P_ID_EMPRESA;
				END
				ELSE
					INSERT INTO T_EMPRESA_CODIGO (COD_ORCAMENTO, ID_EMPRESA) VALUES (1, @P_ID_EMPRESA);
			END

			IF @P_TIPO_CODIGO = @V_TIPO_PEDIDO
			BEGIN

				IF (SELECT COUNT(1) FROM T_EMPRESA_CODIGO WHERE ID_EMPRESA = @P_ID_EMPRESA) > 0 							
				BEGIN
					UPDATE T_EMPRESA_CODIGO SET COD_PEDIDO = ISNULL(COD_PEDIDO, 0) + 1  WHERE ID_EMPRESA = @P_ID_EMPRESA;
				END
				ELSE
					INSERT INTO T_EMPRESA_CODIGO (COD_PEDIDO, ID_EMPRESA) VALUES (1, @P_ID_EMPRESA);
			END

		SET @P_CODIGO = 
			CASE @P_TIPO_CODIGO 
			WHEN @V_TIPO_PRODUTO THEN 
				(SELECT COD_PRODUTO FROM T_EMPRESA_CODIGO WHERE ID_EMPRESA = @P_ID_EMPRESA)
			WHEN @V_TIPO_FORNECEDOR THEN 
				(SELECT COD_FORNECEDOR FROM T_EMPRESA_CODIGO WHERE ID_EMPRESA = @P_ID_EMPRESA)
			WHEN @V_TIPO_CLIENTE THEN 
				(SELECT COD_CLIENTE FROM T_EMPRESA_CODIGO WHERE ID_EMPRESA = @P_ID_EMPRESA)
			WHEN @V_TIPO_ORCAMENTO THEN 
				(SELECT COD_ORCAMENTO FROM T_EMPRESA_CODIGO WHERE ID_EMPRESA = @P_ID_EMPRESA)
			WHEN @V_TIPO_PEDIDO THEN 
				(SELECT COD_PEDIDO FROM T_EMPRESA_CODIGO WHERE ID_EMPRESA = @P_ID_EMPRESA)
			ELSE 1
			END;

		COMMIT TRAN CODIGO;
	END
