
-- --------------------------------------------------
-- Entity Designer DDL Script for SQL Server 2005, 2008, and Azure
-- --------------------------------------------------
-- Date Created: 08/15/2014 02:25:33
-- Generated from EDMX file: C:\Users\MagnumMartins\Documents\GitHub\BrasilDidaticos\BrasilDidaticos.WcfServico\Dados\BrasilDidaticos.edmx
-- --------------------------------------------------

SET QUOTED_IDENTIFIER OFF;
GO
USE [BRASIL_DIDATICOS];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[FK_T_CLIENTE_MATRIZ_T_CLIENTE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_CLIENTE] DROP CONSTRAINT [FK_T_CLIENTE_MATRIZ_T_CLIENTE];
GO
IF OBJECT_ID(N'[dbo].[FK_T_CLIENTE_T_EMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_CLIENTE] DROP CONSTRAINT [FK_T_CLIENTE_T_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_T_ESTADO_ORCAMENTO_T_ESTADO_ORCAMENTO_ANTERIOR]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_ESTADO_ORCAMENTO] DROP CONSTRAINT [FK_T_ESTADO_ORCAMENTO_T_ESTADO_ORCAMENTO_ANTERIOR];
GO
IF OBJECT_ID(N'[dbo].[FK_T_ESTADO_ORCAMENTO_T_ESTADO_ORCAMENTO_SUCESSOR]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_ESTADO_ORCAMENTO] DROP CONSTRAINT [FK_T_ESTADO_ORCAMENTO_T_ESTADO_ORCAMENTO_SUCESSOR];
GO
IF OBJECT_ID(N'[dbo].[FK_T_ESTADO_PEDIDO_T_ESTADO_PEDIDO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_ESTADO_PEDIDO] DROP CONSTRAINT [FK_T_ESTADO_PEDIDO_T_ESTADO_PEDIDO];
GO
IF OBJECT_ID(N'[dbo].[FK_T_ESTADO_PEDIDO_T_ESTADO_PEDIDO1]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_ESTADO_PEDIDO] DROP CONSTRAINT [FK_T_ESTADO_PEDIDO_T_ESTADO_PEDIDO1];
GO
IF OBJECT_ID(N'[dbo].[FK_T_FORNECEDOR_T_EMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_FORNECEDOR] DROP CONSTRAINT [FK_T_FORNECEDOR_T_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_T_FORNECEDOR_TAXA_T_FORNECEDOR]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_FORNECEDOR_TAXA] DROP CONSTRAINT [FK_T_FORNECEDOR_TAXA_T_FORNECEDOR];
GO
IF OBJECT_ID(N'[dbo].[FK_T_FORNECEDOR_TAXA_T_TAXA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_FORNECEDOR_TAXA] DROP CONSTRAINT [FK_T_FORNECEDOR_TAXA_T_TAXA];
GO
IF OBJECT_ID(N'[dbo].[FK_T_ITEM_PEDIDO_T_PEDIDO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_ITEM_PEDIDO] DROP CONSTRAINT [FK_T_ITEM_PEDIDO_T_PEDIDO];
GO
IF OBJECT_ID(N'[dbo].[FK_T_ITEM_PEDIDO_T_PRODUTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_ITEM_PEDIDO] DROP CONSTRAINT [FK_T_ITEM_PEDIDO_T_PRODUTO];
GO
IF OBJECT_ID(N'[dbo].[FK_T_ITEM_PEDIDO_T_UNIDADE_MEDIDA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_ITEM_PEDIDO] DROP CONSTRAINT [FK_T_ITEM_PEDIDO_T_UNIDADE_MEDIDA];
GO
IF OBJECT_ID(N'[dbo].[FK_T_ITEM_T_ORCAMENTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_ITEM] DROP CONSTRAINT [FK_T_ITEM_T_ORCAMENTO];
GO
IF OBJECT_ID(N'[dbo].[FK_T_ITEM_T_PRODUTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_ITEM] DROP CONSTRAINT [FK_T_ITEM_T_PRODUTO];
GO
IF OBJECT_ID(N'[dbo].[FK_T_ITEM_T_UNIDADE_MEDIDA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_ITEM] DROP CONSTRAINT [FK_T_ITEM_T_UNIDADE_MEDIDA];
GO
IF OBJECT_ID(N'[dbo].[FK_T_ORCAMENTO_T_CLIENTE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_ORCAMENTO] DROP CONSTRAINT [FK_T_ORCAMENTO_T_CLIENTE];
GO
IF OBJECT_ID(N'[dbo].[FK_T_ORCAMENTO_T_EMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_ORCAMENTO] DROP CONSTRAINT [FK_T_ORCAMENTO_T_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_T_ORCAMENTO_T_ESTADO_ORCAMENTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_ORCAMENTO] DROP CONSTRAINT [FK_T_ORCAMENTO_T_ESTADO_ORCAMENTO];
GO
IF OBJECT_ID(N'[dbo].[FK_T_ORCAMENTO_T_USUARIO_RESPONSAVEL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_ORCAMENTO] DROP CONSTRAINT [FK_T_ORCAMENTO_T_USUARIO_RESPONSAVEL];
GO
IF OBJECT_ID(N'[dbo].[FK_T_ORCAMENTO_T_USUARIO_VENDEDOR]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_ORCAMENTO] DROP CONSTRAINT [FK_T_ORCAMENTO_T_USUARIO_VENDEDOR];
GO
IF OBJECT_ID(N'[dbo].[FK_T_PARAMETRO_T_EMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_PARAMETRO] DROP CONSTRAINT [FK_T_PARAMETRO_T_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_T_PEDIDO_T_EMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_PEDIDO] DROP CONSTRAINT [FK_T_PEDIDO_T_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_T_PEDIDO_T_ESTADO_PEDIDO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_PEDIDO] DROP CONSTRAINT [FK_T_PEDIDO_T_ESTADO_PEDIDO];
GO
IF OBJECT_ID(N'[dbo].[FK_T_PEDIDO_T_USUARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_PEDIDO] DROP CONSTRAINT [FK_T_PEDIDO_T_USUARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_T_PERFIL_PERMISSAO_T_PERFIL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_PERFIL_PERMISSAO] DROP CONSTRAINT [FK_T_PERFIL_PERMISSAO_T_PERFIL];
GO
IF OBJECT_ID(N'[dbo].[FK_T_PERFIL_PERMISSAO_T_PERMISSAO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_PERFIL_PERMISSAO] DROP CONSTRAINT [FK_T_PERFIL_PERMISSAO_T_PERMISSAO];
GO
IF OBJECT_ID(N'[dbo].[FK_T_PERFIL_T_EMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_PERFIL] DROP CONSTRAINT [FK_T_PERFIL_T_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_T_PRODUTO_T_FORNECEDOR]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_PRODUTO] DROP CONSTRAINT [FK_T_PRODUTO_T_FORNECEDOR];
GO
IF OBJECT_ID(N'[dbo].[FK_T_PRODUTO_TAXA_T_PRODUTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_PRODUTO_TAXA] DROP CONSTRAINT [FK_T_PRODUTO_TAXA_T_PRODUTO];
GO
IF OBJECT_ID(N'[dbo].[FK_T_PRODUTO_TAXA_T_TAXA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_PRODUTO_TAXA] DROP CONSTRAINT [FK_T_PRODUTO_TAXA_T_TAXA];
GO
IF OBJECT_ID(N'[dbo].[FK_T_PRODUTO_UNIDADE_MEDIDA_T_PRODUTO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_PRODUTO_UNIDADE_MEDIDA] DROP CONSTRAINT [FK_T_PRODUTO_UNIDADE_MEDIDA_T_PRODUTO];
GO
IF OBJECT_ID(N'[dbo].[FK_T_PRODUTO_UNIDADE_MEDIDA_T_UNIDADE_MEDIDA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_PRODUTO_UNIDADE_MEDIDA] DROP CONSTRAINT [FK_T_PRODUTO_UNIDADE_MEDIDA_T_UNIDADE_MEDIDA];
GO
IF OBJECT_ID(N'[dbo].[FK_T_TAXA_T_EMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_TAXA] DROP CONSTRAINT [FK_T_TAXA_T_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_T_UNIDADE_MEDIDA_T_EMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_UNIDADE_MEDIDA] DROP CONSTRAINT [FK_T_UNIDADE_MEDIDA_T_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[FK_T_USUARIO_PERFIL_T_PERFIL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_USUARIO_PERFIL] DROP CONSTRAINT [FK_T_USUARIO_PERFIL_T_PERFIL];
GO
IF OBJECT_ID(N'[dbo].[FK_T_USUARIO_PERFIL_T_USUARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_USUARIO_PERFIL] DROP CONSTRAINT [FK_T_USUARIO_PERFIL_T_USUARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_T_USUARIO_T_EMPRESA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[T_USUARIO] DROP CONSTRAINT [FK_T_USUARIO_T_EMPRESA];
GO

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[T_CLIENTE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_CLIENTE];
GO
IF OBJECT_ID(N'[dbo].[T_EMPRESA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_EMPRESA];
GO
IF OBJECT_ID(N'[dbo].[T_ESTADO_ORCAMENTO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_ESTADO_ORCAMENTO];
GO
IF OBJECT_ID(N'[dbo].[T_ESTADO_PEDIDO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_ESTADO_PEDIDO];
GO
IF OBJECT_ID(N'[dbo].[T_FORNECEDOR]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_FORNECEDOR];
GO
IF OBJECT_ID(N'[dbo].[T_FORNECEDOR_TAXA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_FORNECEDOR_TAXA];
GO
IF OBJECT_ID(N'[dbo].[T_ITEM]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_ITEM];
GO
IF OBJECT_ID(N'[dbo].[T_ITEM_PEDIDO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_ITEM_PEDIDO];
GO
IF OBJECT_ID(N'[dbo].[T_ORCAMENTO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_ORCAMENTO];
GO
IF OBJECT_ID(N'[dbo].[T_PARAMETRO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_PARAMETRO];
GO
IF OBJECT_ID(N'[dbo].[T_PEDIDO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_PEDIDO];
GO
IF OBJECT_ID(N'[dbo].[T_PERFIL]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_PERFIL];
GO
IF OBJECT_ID(N'[dbo].[T_PERFIL_PERMISSAO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_PERFIL_PERMISSAO];
GO
IF OBJECT_ID(N'[dbo].[T_PERMISSAO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_PERMISSAO];
GO
IF OBJECT_ID(N'[dbo].[T_PRODUTO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_PRODUTO];
GO
IF OBJECT_ID(N'[dbo].[T_PRODUTO_TAXA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_PRODUTO_TAXA];
GO
IF OBJECT_ID(N'[dbo].[T_PRODUTO_UNIDADE_MEDIDA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_PRODUTO_UNIDADE_MEDIDA];
GO
IF OBJECT_ID(N'[dbo].[T_SESSAO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_SESSAO];
GO
IF OBJECT_ID(N'[dbo].[T_TAXA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_TAXA];
GO
IF OBJECT_ID(N'[dbo].[T_UNIDADE_FEDERATIVA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_UNIDADE_FEDERATIVA];
GO
IF OBJECT_ID(N'[dbo].[T_UNIDADE_MEDIDA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_UNIDADE_MEDIDA];
GO
IF OBJECT_ID(N'[dbo].[T_USUARIO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_USUARIO];
GO
IF OBJECT_ID(N'[dbo].[T_USUARIO_PERFIL]', 'U') IS NOT NULL
    DROP TABLE [dbo].[T_USUARIO_PERFIL];
GO

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'T_CLIENTE'
CREATE TABLE [dbo].[T_CLIENTE] (
    [ID_CLIENTE] uniqueidentifier  NOT NULL,
    [COD_CLIENTE] varchar(20)  NULL,
    [NOME_CLIENTE] varchar(100)  NOT NULL,
    [CAIXA_ESCOLAR] varchar(100)  NULL,
    [BOL_PESSOA_FISICA] bit  NOT NULL,
    [CPF_CNJP_CLIENTE] varchar(14)  NOT NULL,
    [DES_INSCRICAO_ESTADUAL] varchar(30)  NULL,
    [NUM_TELEFONE] varchar(12)  NULL,
    [NUM_CELULAR] varchar(12)  NULL,
    [DES_ENDERECO] varchar(300)  NULL,
    [NUM_ENDERECO] int  NULL,
    [CMP_ENDERECO] varchar(100)  NULL,
    [NUM_CEP] varchar(8)  NULL,
    [DES_BAIRRO] varchar(100)  NULL,
    [DES_CIDADE] varchar(50)  NULL,
    [COD_ESTADO] varchar(2)  NULL,
    [DES_ESTADO] varchar(30)  NULL,
    [DES_EMAIL] varchar(100)  NULL,
    [DATA_ATUALIZACAO] datetime  NOT NULL,
    [LOGIN_USUARIO] varchar(20)  NOT NULL,
    [ID_CLIENTE_MATRIZ] uniqueidentifier  NULL,
    [BOL_ATIVO] bit  NOT NULL,
    [ID_EMPRESA] uniqueidentifier  NOT NULL
);
GO

-- Creating table 'T_FORNECEDOR'
CREATE TABLE [dbo].[T_FORNECEDOR] (
    [ID_FORNECEDOR] uniqueidentifier  NOT NULL,
    [COD_FORNECEDOR] varchar(10)  NOT NULL,
    [NOME_FORNECEDOR] varchar(50)  NOT NULL,
    [BOL_PESSOA_FISICA] bit  NOT NULL,
    [CPF_CNJP_FORNECEDOR] varchar(14)  NULL,
    [NUM_VALOR_VAREJO] decimal(19,4)  NULL,
    [NUM_VALOR_ATACADO] decimal(19,4)  NULL,
    [BOL_ATIVO] bit  NOT NULL,
    [DATA_ATUALIZACAO] datetime  NOT NULL,
    [LOGIN_USUARIO] varchar(20)  NOT NULL,
    [ID_EMPRESA] uniqueidentifier  NOT NULL
);
GO

-- Creating table 'T_FORNECEDOR_TAXA'
CREATE TABLE [dbo].[T_FORNECEDOR_TAXA] (
    [ID_FORNECEDOR_TAXA] uniqueidentifier  NOT NULL,
    [ID_FORNECEDOR] uniqueidentifier  NOT NULL,
    [ID_TAXA] uniqueidentifier  NOT NULL,
    [NUM_VALOR] decimal(19,4)  NOT NULL,
    [ORD_PRIORIDADE] smallint  NOT NULL,
    [LOGIN_USUARIO] varchar(20)  NOT NULL,
    [DATA_ATUALIZACAO] datetime  NOT NULL
);
GO

-- Creating table 'T_ITEM'
CREATE TABLE [dbo].[T_ITEM] (
    [ID_ITEM] uniqueidentifier  NOT NULL,
    [ID_PRODUTO] uniqueidentifier  NOT NULL,
    [ID_ORCAMENTO] uniqueidentifier  NOT NULL,
    [NUM_VALOR_CUSTO] decimal(19,4)  NOT NULL,
    [NUM_DESCONTO] decimal(19,4)  NULL,
    [NUM_QUANTIDADE] int  NOT NULL,
    [DATA_ATUALIZACAO] datetime  NOT NULL,
    [LOGIN_USUARIO] varchar(20)  NOT NULL,
    [DES_ITEM] varchar(300)  NULL,
    [NUM_VALOR_UNITARIO] decimal(19,4)  NOT NULL,
    [ID_UNIDADE_MEDIDA] uniqueidentifier  NULL
);
GO

-- Creating table 'T_ORCAMENTO'
CREATE TABLE [dbo].[T_ORCAMENTO] (
    [ID_ORCAMENTO] uniqueidentifier  NOT NULL,
    [COD_ORCAMENTO] varchar(15)  NOT NULL,
    [DATA_ORCAMENTO] datetime  NOT NULL,
    [ID_CLIENTE] uniqueidentifier  NOT NULL,
    [ID_USUARIO_RESPONSAVEL] uniqueidentifier  NOT NULL,
    [NUM_DESCONTO] decimal(19,4)  NULL,
    [LOGIN_USUARIO] varchar(20)  NOT NULL,
    [DATA_ATUALIZACAO] datetime  NOT NULL,
    [ID_USUARIO_VENDEDOR] uniqueidentifier  NOT NULL,
    [ID_ESTADO_ORCAMENTO] uniqueidentifier  NOT NULL,
    [NUM_VALIDADE_ORCAMENTO] int  NULL,
    [NUM_PRAZO_ENTREGA] int  NULL,
    [ID_EMPRESA] uniqueidentifier  NOT NULL
);
GO

-- Creating table 'T_PARAMETRO'
CREATE TABLE [dbo].[T_PARAMETRO] (
    [ID_PARAMETRO] uniqueidentifier  NOT NULL,
    [COD_PARAMETRO] varchar(20)  NOT NULL,
    [NOME_PARAMETRO] varchar(30)  NOT NULL,
    [TIPO_PARAMETRO] varchar(20)  NOT NULL,
    [VALOR_PARAMETRO] varchar(50)  NOT NULL,
    [LOGIN_USUARIO] varchar(20)  NOT NULL,
    [DATA_ATUALIZACAO] datetime  NOT NULL,
    [NUM_ORDEM] int  NULL,
    [ID_EMPRESA] uniqueidentifier  NOT NULL
);
GO

-- Creating table 'T_PERFIL'
CREATE TABLE [dbo].[T_PERFIL] (
    [ID_PERFIL] uniqueidentifier  NOT NULL,
    [COD_PERFIL] varchar(10)  NOT NULL,
    [NOME_PERFIL] varchar(30)  NOT NULL,
    [BOL_ATIVO] bit  NOT NULL,
    [LOGIN_USUARIO] varchar(20)  NULL,
    [DATA_ATUALIZACAO] datetime  NULL,
    [ID_EMPRESA] uniqueidentifier  NOT NULL,
    [DES_PERFIL] varchar(300)  NULL
);
GO

-- Creating table 'T_PERFIL_PERMISSAO'
CREATE TABLE [dbo].[T_PERFIL_PERMISSAO] (
    [ID_PERFIL_PERMISSAO] uniqueidentifier  NOT NULL,
    [ID_PERFIL] uniqueidentifier  NOT NULL,
    [ID_PERMISSAO] uniqueidentifier  NOT NULL,
    [DATA_ATUALIZACAO] datetime  NOT NULL,
    [LOGIN_USUARIO] varchar(20)  NOT NULL
);
GO

-- Creating table 'T_PERMISSAO'
CREATE TABLE [dbo].[T_PERMISSAO] (
    [ID_PERMISSAO] uniqueidentifier  NOT NULL,
    [NOME_PERMISSAO] varchar(30)  NOT NULL,
    [BOL_ATIVO] bit  NOT NULL
);
GO

-- Creating table 'T_PRODUTO'
CREATE TABLE [dbo].[T_PRODUTO] (
    [ID_PRODUTO] uniqueidentifier  NOT NULL,
    [ID_FORNECEDOR] uniqueidentifier  NOT NULL,
    [COD_PRODUTO] varchar(10)  NULL,
    [NOME_PRODUTO] varchar(100)  NOT NULL,
    [NCM_PRODUTO] varchar(20)  NULL,
    [BOL_ATIVO] bit  NOT NULL,
    [DATA_ATUALIZACAO] datetime  NOT NULL,
    [LOGIN_USUARIO] varchar(20)  NOT NULL,
    [NUM_VALOR] decimal(19,4)  NOT NULL,
    [COD_PRODUTO_FORNECEDOR] varchar(20)  NULL,
    [NUM_QUANTIDADE] int  NOT NULL,
    [COD_BARRAS] varchar(50)  NULL,
    [NUM_VALOR_VAREJO] decimal(19,4)  NULL,
    [NUM_VALOR_ATACADO] decimal(19,4)  NULL
);
GO

-- Creating table 'T_PRODUTO_TAXA'
CREATE TABLE [dbo].[T_PRODUTO_TAXA] (
    [ID_PRODUTO_TAXA] uniqueidentifier  NOT NULL,
    [ID_PRODUTO] uniqueidentifier  NOT NULL,
    [ID_TAXA] uniqueidentifier  NOT NULL,
    [NUM_VALOR] decimal(19,4)  NOT NULL,
    [ORD_PRIORIDADE] smallint  NOT NULL,
    [LOGIN_USUARIO] varchar(20)  NOT NULL,
    [DATA_ATUALIZACAO] datetime  NOT NULL
);
GO

-- Creating table 'T_SESSAO'
CREATE TABLE [dbo].[T_SESSAO] (
    [ID_SESSAO] uniqueidentifier  NOT NULL,
    [LOGIN_USUARIO] varchar(20)  NOT NULL,
    [DATA_LOGIN] datetime  NOT NULL,
    [DES_CHAVE] varchar(32)  NOT NULL
);
GO

-- Creating table 'T_TAXA'
CREATE TABLE [dbo].[T_TAXA] (
    [ID_TAXA] uniqueidentifier  NOT NULL,
    [NOME_TAXA] varchar(20)  NOT NULL,
    [BOL_FORNECEDOR] bit  NULL,
    [BOL_PRODUTO] bit  NULL,
    [BOL_DESCONTO] bit  NULL,
    [BOL_ATIVO] bit  NOT NULL,
    [DATA_ATUALIZACAO] datetime  NOT NULL,
    [LOGIN_USUARIO] varchar(20)  NOT NULL,
    [ID_EMPRESA] uniqueidentifier  NOT NULL,
    [DES_TAXA] varchar(300)  NULL
);
GO

-- Creating table 'T_USUARIO'
CREATE TABLE [dbo].[T_USUARIO] (
    [ID_USUARIO] uniqueidentifier  NOT NULL,
    [NOME_USUARIO] varchar(50)  NOT NULL,
    [LOGIN_USUARIO] varchar(20)  NOT NULL,
    [SENHA_USUARIO] varchar(32)  NOT NULL,
    [BOL_ATIVO] bit  NOT NULL,
    [DATA_ATUALIZACAO] datetime  NOT NULL,
    [USUARIO_LOGADO] varchar(20)  NOT NULL,
    [ID_EMPRESA] uniqueidentifier  NOT NULL
);
GO

-- Creating table 'T_USUARIO_PERFIL'
CREATE TABLE [dbo].[T_USUARIO_PERFIL] (
    [ID_USUARIO_PERFIL] uniqueidentifier  NOT NULL,
    [ID_USUARIO] uniqueidentifier  NOT NULL,
    [ID_PERFIL] uniqueidentifier  NOT NULL,
    [DATA_ATUALIZACAO] datetime  NOT NULL,
    [LOGIN_USUARIO] varchar(20)  NOT NULL
);
GO

-- Creating table 'T_UNIDADE_FEDERATIVA'
CREATE TABLE [dbo].[T_UNIDADE_FEDERATIVA] (
    [ID_UNIDADE_FEDERATIVA] uniqueidentifier  NOT NULL,
    [COD_UNIDADE_FEDERATIVA] char(2)  NOT NULL,
    [NOME_UNIDADE_FEDERATIVA] varchar(30)  NOT NULL
);
GO

-- Creating table 'T_ESTADO_ORCAMENTO'
CREATE TABLE [dbo].[T_ESTADO_ORCAMENTO] (
    [ID_ESTADO_ORCAMENTO] uniqueidentifier  NOT NULL,
    [COD_ESTADO_ORCAMENTO] char(2)  NOT NULL,
    [NOME_ESTADO_ORCAMENTO] varchar(30)  NOT NULL,
    [BOL_ATIVO] bit  NOT NULL,
    [ID_ESTADO_ORCAMENTO_ANTERIOR] uniqueidentifier  NULL,
    [ID_ESTADO_ORCAMENTO_SUCESSOR] uniqueidentifier  NULL
);
GO

-- Creating table 'T_EMPRESA'
CREATE TABLE [dbo].[T_EMPRESA] (
    [ID_EMPRESA] uniqueidentifier  NOT NULL,
    [COD_EMPRESA] varchar(20)  NOT NULL,
    [NOME_EMPRESA] varchar(100)  NOT NULL,
    [BOL_ATIVO] bit  NOT NULL
);
GO

-- Creating table 'T_UNIDADE_MEDIDA'
CREATE TABLE [dbo].[T_UNIDADE_MEDIDA] (
    [ID_UNIDADE_MEDIDA] uniqueidentifier  NOT NULL,
    [ID_EMPRESA] uniqueidentifier  NOT NULL,
    [NOME_UNIDADE_MEDIDA] varchar(20)  NOT NULL,
    [DES_UNIDADE_MEDIDA] varchar(300)  NULL,
    [BOL_ATIVO] bit  NOT NULL,
    [DATA_ATUALIZACAO] datetime  NOT NULL,
    [LOGIN_USUARIO] varchar(20)  NOT NULL,
    [COD_UNIDADE_MEDIDA] varchar(20)  NOT NULL
);
GO

-- Creating table 'T_ESTADO_PEDIDO'
CREATE TABLE [dbo].[T_ESTADO_PEDIDO] (
    [ID_ESTADO_PEDIDO] uniqueidentifier  NOT NULL,
    [COD_ESTADO_PEDIDO] char(2)  NOT NULL,
    [NOME_ESTADO_PEDIDO] varchar(30)  NOT NULL,
    [BOL_ATIVO] bit  NOT NULL,
    [ID_ESTADO_PEDIDO_ANTERIOR] uniqueidentifier  NULL,
    [ID_ESTADO_PEDIDO_SUCESSOR] uniqueidentifier  NULL
);
GO

-- Creating table 'T_ITEM_PEDIDO'
CREATE TABLE [dbo].[T_ITEM_PEDIDO] (
    [ID_ITEM_PEDIDO] uniqueidentifier  NOT NULL,
    [ID_PRODUTO] uniqueidentifier  NULL,
    [ID_PEDIDO] uniqueidentifier  NOT NULL,
    [NUM_VALOR] decimal(19,4)  NOT NULL,
    [NUM_DESCONTO] decimal(19,4)  NULL,
    [NUM_QUANTIDADE] int  NOT NULL,
    [DATA_ATUALIZACAO] datetime  NOT NULL,
    [LOGIN_USUARIO] varchar(20)  NOT NULL,
    [ID_UNIDADE_MEDIDA] uniqueidentifier  NULL
);
GO

-- Creating table 'T_PEDIDO'
CREATE TABLE [dbo].[T_PEDIDO] (
    [ID_PEDIDO] uniqueidentifier  NOT NULL,
    [ID_EMPRESA] uniqueidentifier  NOT NULL,
    [COD_PEDIDO] varchar(15)  NOT NULL,
    [DATA_PEDIDO] datetime  NOT NULL,
    [ID_ESTADO_PEDIDO] uniqueidentifier  NOT NULL,
    [ID_USUARIO_RESPONSAVEL] uniqueidentifier  NOT NULL,
    [NUM_DESCONTO] decimal(19,4)  NULL,
    [LOGIN_USUARIO] varchar(20)  NOT NULL,
    [DATA_ATUALIZACAO] datetime  NOT NULL
);
GO

-- Creating table 'T_PRODUTO_UNIDADE_MEDIDA'
CREATE TABLE [dbo].[T_PRODUTO_UNIDADE_MEDIDA] (
    [ID_PRODUTO_UNIDADE_MEDIDA] uniqueidentifier  NOT NULL,
    [ID_PRODUTO] uniqueidentifier  NOT NULL,
    [ID_UNIDADE_MEDIDA] uniqueidentifier  NOT NULL,
    [NUM_QUANTIDADE_ITEM] int  NOT NULL,
    [LOGIN_USUARIO] varchar(20)  NOT NULL,
    [DATA_ATUALIZACAO] datetime  NOT NULL,
    [NUM_QUANTIDADE] int  NOT NULL
);
GO

-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on [ID_CLIENTE] in table 'T_CLIENTE'
ALTER TABLE [dbo].[T_CLIENTE]
ADD CONSTRAINT [PK_T_CLIENTE]
    PRIMARY KEY CLUSTERED ([ID_CLIENTE] ASC);
GO

-- Creating primary key on [ID_FORNECEDOR] in table 'T_FORNECEDOR'
ALTER TABLE [dbo].[T_FORNECEDOR]
ADD CONSTRAINT [PK_T_FORNECEDOR]
    PRIMARY KEY CLUSTERED ([ID_FORNECEDOR] ASC);
GO

-- Creating primary key on [ID_FORNECEDOR_TAXA] in table 'T_FORNECEDOR_TAXA'
ALTER TABLE [dbo].[T_FORNECEDOR_TAXA]
ADD CONSTRAINT [PK_T_FORNECEDOR_TAXA]
    PRIMARY KEY CLUSTERED ([ID_FORNECEDOR_TAXA] ASC);
GO

-- Creating primary key on [ID_ITEM] in table 'T_ITEM'
ALTER TABLE [dbo].[T_ITEM]
ADD CONSTRAINT [PK_T_ITEM]
    PRIMARY KEY CLUSTERED ([ID_ITEM] ASC);
GO

-- Creating primary key on [ID_ORCAMENTO] in table 'T_ORCAMENTO'
ALTER TABLE [dbo].[T_ORCAMENTO]
ADD CONSTRAINT [PK_T_ORCAMENTO]
    PRIMARY KEY CLUSTERED ([ID_ORCAMENTO] ASC);
GO

-- Creating primary key on [ID_PARAMETRO] in table 'T_PARAMETRO'
ALTER TABLE [dbo].[T_PARAMETRO]
ADD CONSTRAINT [PK_T_PARAMETRO]
    PRIMARY KEY CLUSTERED ([ID_PARAMETRO] ASC);
GO

-- Creating primary key on [ID_PERFIL] in table 'T_PERFIL'
ALTER TABLE [dbo].[T_PERFIL]
ADD CONSTRAINT [PK_T_PERFIL]
    PRIMARY KEY CLUSTERED ([ID_PERFIL] ASC);
GO

-- Creating primary key on [ID_PERFIL_PERMISSAO] in table 'T_PERFIL_PERMISSAO'
ALTER TABLE [dbo].[T_PERFIL_PERMISSAO]
ADD CONSTRAINT [PK_T_PERFIL_PERMISSAO]
    PRIMARY KEY CLUSTERED ([ID_PERFIL_PERMISSAO] ASC);
GO

-- Creating primary key on [ID_PERMISSAO] in table 'T_PERMISSAO'
ALTER TABLE [dbo].[T_PERMISSAO]
ADD CONSTRAINT [PK_T_PERMISSAO]
    PRIMARY KEY CLUSTERED ([ID_PERMISSAO] ASC);
GO

-- Creating primary key on [ID_PRODUTO] in table 'T_PRODUTO'
ALTER TABLE [dbo].[T_PRODUTO]
ADD CONSTRAINT [PK_T_PRODUTO]
    PRIMARY KEY CLUSTERED ([ID_PRODUTO] ASC);
GO

-- Creating primary key on [ID_PRODUTO_TAXA] in table 'T_PRODUTO_TAXA'
ALTER TABLE [dbo].[T_PRODUTO_TAXA]
ADD CONSTRAINT [PK_T_PRODUTO_TAXA]
    PRIMARY KEY CLUSTERED ([ID_PRODUTO_TAXA] ASC);
GO

-- Creating primary key on [ID_SESSAO] in table 'T_SESSAO'
ALTER TABLE [dbo].[T_SESSAO]
ADD CONSTRAINT [PK_T_SESSAO]
    PRIMARY KEY CLUSTERED ([ID_SESSAO] ASC);
GO

-- Creating primary key on [ID_TAXA] in table 'T_TAXA'
ALTER TABLE [dbo].[T_TAXA]
ADD CONSTRAINT [PK_T_TAXA]
    PRIMARY KEY CLUSTERED ([ID_TAXA] ASC);
GO

-- Creating primary key on [ID_USUARIO] in table 'T_USUARIO'
ALTER TABLE [dbo].[T_USUARIO]
ADD CONSTRAINT [PK_T_USUARIO]
    PRIMARY KEY CLUSTERED ([ID_USUARIO] ASC);
GO

-- Creating primary key on [ID_USUARIO_PERFIL] in table 'T_USUARIO_PERFIL'
ALTER TABLE [dbo].[T_USUARIO_PERFIL]
ADD CONSTRAINT [PK_T_USUARIO_PERFIL]
    PRIMARY KEY CLUSTERED ([ID_USUARIO_PERFIL] ASC);
GO

-- Creating primary key on [ID_UNIDADE_FEDERATIVA] in table 'T_UNIDADE_FEDERATIVA'
ALTER TABLE [dbo].[T_UNIDADE_FEDERATIVA]
ADD CONSTRAINT [PK_T_UNIDADE_FEDERATIVA]
    PRIMARY KEY CLUSTERED ([ID_UNIDADE_FEDERATIVA] ASC);
GO

-- Creating primary key on [ID_ESTADO_ORCAMENTO] in table 'T_ESTADO_ORCAMENTO'
ALTER TABLE [dbo].[T_ESTADO_ORCAMENTO]
ADD CONSTRAINT [PK_T_ESTADO_ORCAMENTO]
    PRIMARY KEY CLUSTERED ([ID_ESTADO_ORCAMENTO] ASC);
GO

-- Creating primary key on [ID_EMPRESA] in table 'T_EMPRESA'
ALTER TABLE [dbo].[T_EMPRESA]
ADD CONSTRAINT [PK_T_EMPRESA]
    PRIMARY KEY CLUSTERED ([ID_EMPRESA] ASC);
GO

-- Creating primary key on [ID_UNIDADE_MEDIDA] in table 'T_UNIDADE_MEDIDA'
ALTER TABLE [dbo].[T_UNIDADE_MEDIDA]
ADD CONSTRAINT [PK_T_UNIDADE_MEDIDA]
    PRIMARY KEY CLUSTERED ([ID_UNIDADE_MEDIDA] ASC);
GO

-- Creating primary key on [ID_ESTADO_PEDIDO] in table 'T_ESTADO_PEDIDO'
ALTER TABLE [dbo].[T_ESTADO_PEDIDO]
ADD CONSTRAINT [PK_T_ESTADO_PEDIDO]
    PRIMARY KEY CLUSTERED ([ID_ESTADO_PEDIDO] ASC);
GO

-- Creating primary key on [ID_ITEM_PEDIDO] in table 'T_ITEM_PEDIDO'
ALTER TABLE [dbo].[T_ITEM_PEDIDO]
ADD CONSTRAINT [PK_T_ITEM_PEDIDO]
    PRIMARY KEY CLUSTERED ([ID_ITEM_PEDIDO] ASC);
GO

-- Creating primary key on [ID_PEDIDO] in table 'T_PEDIDO'
ALTER TABLE [dbo].[T_PEDIDO]
ADD CONSTRAINT [PK_T_PEDIDO]
    PRIMARY KEY CLUSTERED ([ID_PEDIDO] ASC);
GO

-- Creating primary key on [ID_PRODUTO_UNIDADE_MEDIDA] in table 'T_PRODUTO_UNIDADE_MEDIDA'
ALTER TABLE [dbo].[T_PRODUTO_UNIDADE_MEDIDA]
ADD CONSTRAINT [PK_T_PRODUTO_UNIDADE_MEDIDA]
    PRIMARY KEY CLUSTERED ([ID_PRODUTO_UNIDADE_MEDIDA] ASC);
GO

-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on [ID_CLIENTE_MATRIZ] in table 'T_CLIENTE'
ALTER TABLE [dbo].[T_CLIENTE]
ADD CONSTRAINT [FK_T_CLIENTE_MATRIZ_T_CLIENTE]
    FOREIGN KEY ([ID_CLIENTE_MATRIZ])
    REFERENCES [dbo].[T_CLIENTE]
        ([ID_CLIENTE])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_CLIENTE_MATRIZ_T_CLIENTE'
CREATE INDEX [IX_FK_T_CLIENTE_MATRIZ_T_CLIENTE]
ON [dbo].[T_CLIENTE]
    ([ID_CLIENTE_MATRIZ]);
GO

-- Creating foreign key on [ID_CLIENTE] in table 'T_ORCAMENTO'
ALTER TABLE [dbo].[T_ORCAMENTO]
ADD CONSTRAINT [FK_T_ORCAMENTO_T_CLIENTE]
    FOREIGN KEY ([ID_CLIENTE])
    REFERENCES [dbo].[T_CLIENTE]
        ([ID_CLIENTE])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_ORCAMENTO_T_CLIENTE'
CREATE INDEX [IX_FK_T_ORCAMENTO_T_CLIENTE]
ON [dbo].[T_ORCAMENTO]
    ([ID_CLIENTE]);
GO

-- Creating foreign key on [ID_FORNECEDOR] in table 'T_FORNECEDOR_TAXA'
ALTER TABLE [dbo].[T_FORNECEDOR_TAXA]
ADD CONSTRAINT [FK_T_FORNECEDOR_TAXA_T_FORNECEDOR]
    FOREIGN KEY ([ID_FORNECEDOR])
    REFERENCES [dbo].[T_FORNECEDOR]
        ([ID_FORNECEDOR])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_FORNECEDOR_TAXA_T_FORNECEDOR'
CREATE INDEX [IX_FK_T_FORNECEDOR_TAXA_T_FORNECEDOR]
ON [dbo].[T_FORNECEDOR_TAXA]
    ([ID_FORNECEDOR]);
GO

-- Creating foreign key on [ID_FORNECEDOR] in table 'T_PRODUTO'
ALTER TABLE [dbo].[T_PRODUTO]
ADD CONSTRAINT [FK_T_PRODUTO_T_FORNECEDOR]
    FOREIGN KEY ([ID_FORNECEDOR])
    REFERENCES [dbo].[T_FORNECEDOR]
        ([ID_FORNECEDOR])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_PRODUTO_T_FORNECEDOR'
CREATE INDEX [IX_FK_T_PRODUTO_T_FORNECEDOR]
ON [dbo].[T_PRODUTO]
    ([ID_FORNECEDOR]);
GO

-- Creating foreign key on [ID_TAXA] in table 'T_FORNECEDOR_TAXA'
ALTER TABLE [dbo].[T_FORNECEDOR_TAXA]
ADD CONSTRAINT [FK_T_FORNECEDOR_TAXA_T_TAXA]
    FOREIGN KEY ([ID_TAXA])
    REFERENCES [dbo].[T_TAXA]
        ([ID_TAXA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_FORNECEDOR_TAXA_T_TAXA'
CREATE INDEX [IX_FK_T_FORNECEDOR_TAXA_T_TAXA]
ON [dbo].[T_FORNECEDOR_TAXA]
    ([ID_TAXA]);
GO

-- Creating foreign key on [ID_ORCAMENTO] in table 'T_ITEM'
ALTER TABLE [dbo].[T_ITEM]
ADD CONSTRAINT [FK_T_ITEM_T_ORCAMENTO]
    FOREIGN KEY ([ID_ORCAMENTO])
    REFERENCES [dbo].[T_ORCAMENTO]
        ([ID_ORCAMENTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_ITEM_T_ORCAMENTO'
CREATE INDEX [IX_FK_T_ITEM_T_ORCAMENTO]
ON [dbo].[T_ITEM]
    ([ID_ORCAMENTO]);
GO

-- Creating foreign key on [ID_PRODUTO] in table 'T_ITEM'
ALTER TABLE [dbo].[T_ITEM]
ADD CONSTRAINT [FK_T_ITEM_T_PRODUTO]
    FOREIGN KEY ([ID_PRODUTO])
    REFERENCES [dbo].[T_PRODUTO]
        ([ID_PRODUTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_ITEM_T_PRODUTO'
CREATE INDEX [IX_FK_T_ITEM_T_PRODUTO]
ON [dbo].[T_ITEM]
    ([ID_PRODUTO]);
GO

-- Creating foreign key on [ID_USUARIO_RESPONSAVEL] in table 'T_ORCAMENTO'
ALTER TABLE [dbo].[T_ORCAMENTO]
ADD CONSTRAINT [FK_T_ORCAMENTO_T_USUARIO]
    FOREIGN KEY ([ID_USUARIO_RESPONSAVEL])
    REFERENCES [dbo].[T_USUARIO]
        ([ID_USUARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_ORCAMENTO_T_USUARIO'
CREATE INDEX [IX_FK_T_ORCAMENTO_T_USUARIO]
ON [dbo].[T_ORCAMENTO]
    ([ID_USUARIO_RESPONSAVEL]);
GO

-- Creating foreign key on [ID_PERFIL] in table 'T_PERFIL_PERMISSAO'
ALTER TABLE [dbo].[T_PERFIL_PERMISSAO]
ADD CONSTRAINT [FK_T_PERFIL_PERMISSAO_T_PERFIL]
    FOREIGN KEY ([ID_PERFIL])
    REFERENCES [dbo].[T_PERFIL]
        ([ID_PERFIL])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_PERFIL_PERMISSAO_T_PERFIL'
CREATE INDEX [IX_FK_T_PERFIL_PERMISSAO_T_PERFIL]
ON [dbo].[T_PERFIL_PERMISSAO]
    ([ID_PERFIL]);
GO

-- Creating foreign key on [ID_PERFIL] in table 'T_USUARIO_PERFIL'
ALTER TABLE [dbo].[T_USUARIO_PERFIL]
ADD CONSTRAINT [FK_T_USUARIO_PERFIL_T_PERFIL]
    FOREIGN KEY ([ID_PERFIL])
    REFERENCES [dbo].[T_PERFIL]
        ([ID_PERFIL])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_USUARIO_PERFIL_T_PERFIL'
CREATE INDEX [IX_FK_T_USUARIO_PERFIL_T_PERFIL]
ON [dbo].[T_USUARIO_PERFIL]
    ([ID_PERFIL]);
GO

-- Creating foreign key on [ID_PERMISSAO] in table 'T_PERFIL_PERMISSAO'
ALTER TABLE [dbo].[T_PERFIL_PERMISSAO]
ADD CONSTRAINT [FK_T_PERFIL_PERMISSAO_T_PERMISSAO]
    FOREIGN KEY ([ID_PERMISSAO])
    REFERENCES [dbo].[T_PERMISSAO]
        ([ID_PERMISSAO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_PERFIL_PERMISSAO_T_PERMISSAO'
CREATE INDEX [IX_FK_T_PERFIL_PERMISSAO_T_PERMISSAO]
ON [dbo].[T_PERFIL_PERMISSAO]
    ([ID_PERMISSAO]);
GO

-- Creating foreign key on [ID_PRODUTO] in table 'T_PRODUTO_TAXA'
ALTER TABLE [dbo].[T_PRODUTO_TAXA]
ADD CONSTRAINT [FK_T_PRODUTO_TAXA_T_PRODUTO]
    FOREIGN KEY ([ID_PRODUTO])
    REFERENCES [dbo].[T_PRODUTO]
        ([ID_PRODUTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_PRODUTO_TAXA_T_PRODUTO'
CREATE INDEX [IX_FK_T_PRODUTO_TAXA_T_PRODUTO]
ON [dbo].[T_PRODUTO_TAXA]
    ([ID_PRODUTO]);
GO

-- Creating foreign key on [ID_TAXA] in table 'T_PRODUTO_TAXA'
ALTER TABLE [dbo].[T_PRODUTO_TAXA]
ADD CONSTRAINT [FK_T_PRODUTO_TAXA_T_TAXA]
    FOREIGN KEY ([ID_TAXA])
    REFERENCES [dbo].[T_TAXA]
        ([ID_TAXA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_PRODUTO_TAXA_T_TAXA'
CREATE INDEX [IX_FK_T_PRODUTO_TAXA_T_TAXA]
ON [dbo].[T_PRODUTO_TAXA]
    ([ID_TAXA]);
GO

-- Creating foreign key on [ID_USUARIO] in table 'T_USUARIO_PERFIL'
ALTER TABLE [dbo].[T_USUARIO_PERFIL]
ADD CONSTRAINT [FK_T_USUARIO_PERFIL_T_USUARIO]
    FOREIGN KEY ([ID_USUARIO])
    REFERENCES [dbo].[T_USUARIO]
        ([ID_USUARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_USUARIO_PERFIL_T_USUARIO'
CREATE INDEX [IX_FK_T_USUARIO_PERFIL_T_USUARIO]
ON [dbo].[T_USUARIO_PERFIL]
    ([ID_USUARIO]);
GO

-- Creating foreign key on [ID_ESTADO_ORCAMENTO_ANTERIOR] in table 'T_ESTADO_ORCAMENTO'
ALTER TABLE [dbo].[T_ESTADO_ORCAMENTO]
ADD CONSTRAINT [FK_T_ESTADO_ORCAMENTO_T_ESTADO_ORCAMENTO_ANTERIOR]
    FOREIGN KEY ([ID_ESTADO_ORCAMENTO_ANTERIOR])
    REFERENCES [dbo].[T_ESTADO_ORCAMENTO]
        ([ID_ESTADO_ORCAMENTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_ESTADO_ORCAMENTO_T_ESTADO_ORCAMENTO_ANTERIOR'
CREATE INDEX [IX_FK_T_ESTADO_ORCAMENTO_T_ESTADO_ORCAMENTO_ANTERIOR]
ON [dbo].[T_ESTADO_ORCAMENTO]
    ([ID_ESTADO_ORCAMENTO_ANTERIOR]);
GO

-- Creating foreign key on [ID_ESTADO_ORCAMENTO_SUCESSOR] in table 'T_ESTADO_ORCAMENTO'
ALTER TABLE [dbo].[T_ESTADO_ORCAMENTO]
ADD CONSTRAINT [FK_T_ESTADO_ORCAMENTO_T_ESTADO_ORCAMENTO_SUCESSOR]
    FOREIGN KEY ([ID_ESTADO_ORCAMENTO_SUCESSOR])
    REFERENCES [dbo].[T_ESTADO_ORCAMENTO]
        ([ID_ESTADO_ORCAMENTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_ESTADO_ORCAMENTO_T_ESTADO_ORCAMENTO_SUCESSOR'
CREATE INDEX [IX_FK_T_ESTADO_ORCAMENTO_T_ESTADO_ORCAMENTO_SUCESSOR]
ON [dbo].[T_ESTADO_ORCAMENTO]
    ([ID_ESTADO_ORCAMENTO_SUCESSOR]);
GO

-- Creating foreign key on [ID_ESTADO_ORCAMENTO] in table 'T_ORCAMENTO'
ALTER TABLE [dbo].[T_ORCAMENTO]
ADD CONSTRAINT [FK_T_ORCAMENTO_T_ESTADO_ORCAMENTO]
    FOREIGN KEY ([ID_ESTADO_ORCAMENTO])
    REFERENCES [dbo].[T_ESTADO_ORCAMENTO]
        ([ID_ESTADO_ORCAMENTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_ORCAMENTO_T_ESTADO_ORCAMENTO'
CREATE INDEX [IX_FK_T_ORCAMENTO_T_ESTADO_ORCAMENTO]
ON [dbo].[T_ORCAMENTO]
    ([ID_ESTADO_ORCAMENTO]);
GO

-- Creating foreign key on [ID_USUARIO_VENDEDOR] in table 'T_ORCAMENTO'
ALTER TABLE [dbo].[T_ORCAMENTO]
ADD CONSTRAINT [FK_T_ORCAMENTO_T_USUARIO_VENDEDOR]
    FOREIGN KEY ([ID_USUARIO_VENDEDOR])
    REFERENCES [dbo].[T_USUARIO]
        ([ID_USUARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_ORCAMENTO_T_USUARIO_VENDEDOR'
CREATE INDEX [IX_FK_T_ORCAMENTO_T_USUARIO_VENDEDOR]
ON [dbo].[T_ORCAMENTO]
    ([ID_USUARIO_VENDEDOR]);
GO

-- Creating foreign key on [ID_EMPRESA] in table 'T_CLIENTE'
ALTER TABLE [dbo].[T_CLIENTE]
ADD CONSTRAINT [FK_T_CLIENTE_T_EMPRESA]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [dbo].[T_EMPRESA]
        ([ID_EMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_CLIENTE_T_EMPRESA'
CREATE INDEX [IX_FK_T_CLIENTE_T_EMPRESA]
ON [dbo].[T_CLIENTE]
    ([ID_EMPRESA]);
GO

-- Creating foreign key on [ID_EMPRESA] in table 'T_FORNECEDOR'
ALTER TABLE [dbo].[T_FORNECEDOR]
ADD CONSTRAINT [FK_T_FORNECEDOR_T_EMPRESA]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [dbo].[T_EMPRESA]
        ([ID_EMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_FORNECEDOR_T_EMPRESA'
CREATE INDEX [IX_FK_T_FORNECEDOR_T_EMPRESA]
ON [dbo].[T_FORNECEDOR]
    ([ID_EMPRESA]);
GO

-- Creating foreign key on [ID_EMPRESA] in table 'T_ORCAMENTO'
ALTER TABLE [dbo].[T_ORCAMENTO]
ADD CONSTRAINT [FK_T_ORCAMENTO_T_EMPRESA]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [dbo].[T_EMPRESA]
        ([ID_EMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_ORCAMENTO_T_EMPRESA'
CREATE INDEX [IX_FK_T_ORCAMENTO_T_EMPRESA]
ON [dbo].[T_ORCAMENTO]
    ([ID_EMPRESA]);
GO

-- Creating foreign key on [ID_EMPRESA] in table 'T_PARAMETRO'
ALTER TABLE [dbo].[T_PARAMETRO]
ADD CONSTRAINT [FK_T_PARAMETRO_T_EMPRESA]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [dbo].[T_EMPRESA]
        ([ID_EMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_PARAMETRO_T_EMPRESA'
CREATE INDEX [IX_FK_T_PARAMETRO_T_EMPRESA]
ON [dbo].[T_PARAMETRO]
    ([ID_EMPRESA]);
GO

-- Creating foreign key on [ID_EMPRESA] in table 'T_PERFIL'
ALTER TABLE [dbo].[T_PERFIL]
ADD CONSTRAINT [FK_T_PERFIL_T_EMPRESA]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [dbo].[T_EMPRESA]
        ([ID_EMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_PERFIL_T_EMPRESA'
CREATE INDEX [IX_FK_T_PERFIL_T_EMPRESA]
ON [dbo].[T_PERFIL]
    ([ID_EMPRESA]);
GO

-- Creating foreign key on [ID_EMPRESA] in table 'T_TAXA'
ALTER TABLE [dbo].[T_TAXA]
ADD CONSTRAINT [FK_T_TAXA_T_EMPRESA]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [dbo].[T_EMPRESA]
        ([ID_EMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_TAXA_T_EMPRESA'
CREATE INDEX [IX_FK_T_TAXA_T_EMPRESA]
ON [dbo].[T_TAXA]
    ([ID_EMPRESA]);
GO

-- Creating foreign key on [ID_EMPRESA] in table 'T_USUARIO'
ALTER TABLE [dbo].[T_USUARIO]
ADD CONSTRAINT [FK_T_USUARIO_T_EMPRESA]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [dbo].[T_EMPRESA]
        ([ID_EMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_USUARIO_T_EMPRESA'
CREATE INDEX [IX_FK_T_USUARIO_T_EMPRESA]
ON [dbo].[T_USUARIO]
    ([ID_EMPRESA]);
GO

-- Creating foreign key on [ID_EMPRESA] in table 'T_UNIDADE_MEDIDA'
ALTER TABLE [dbo].[T_UNIDADE_MEDIDA]
ADD CONSTRAINT [FK_T_UNIDADE_MEDIDA_T_EMPRESA]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [dbo].[T_EMPRESA]
        ([ID_EMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_UNIDADE_MEDIDA_T_EMPRESA'
CREATE INDEX [IX_FK_T_UNIDADE_MEDIDA_T_EMPRESA]
ON [dbo].[T_UNIDADE_MEDIDA]
    ([ID_EMPRESA]);
GO

-- Creating foreign key on [ID_PRODUTO] in table 'T_ITEM_PEDIDO'
ALTER TABLE [dbo].[T_ITEM_PEDIDO]
ADD CONSTRAINT [FK_T_ITEM_PEDIDO_T_PRODUTO]
    FOREIGN KEY ([ID_PRODUTO])
    REFERENCES [dbo].[T_PRODUTO]
        ([ID_PRODUTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_ITEM_PEDIDO_T_PRODUTO'
CREATE INDEX [IX_FK_T_ITEM_PEDIDO_T_PRODUTO]
ON [dbo].[T_ITEM_PEDIDO]
    ([ID_PRODUTO]);
GO

-- Creating foreign key on [ID_EMPRESA] in table 'T_PEDIDO'
ALTER TABLE [dbo].[T_PEDIDO]
ADD CONSTRAINT [FK_T_PEDIDO_T_EMPRESA]
    FOREIGN KEY ([ID_EMPRESA])
    REFERENCES [dbo].[T_EMPRESA]
        ([ID_EMPRESA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_PEDIDO_T_EMPRESA'
CREATE INDEX [IX_FK_T_PEDIDO_T_EMPRESA]
ON [dbo].[T_PEDIDO]
    ([ID_EMPRESA]);
GO

-- Creating foreign key on [ID_ESTADO_PEDIDO] in table 'T_PEDIDO'
ALTER TABLE [dbo].[T_PEDIDO]
ADD CONSTRAINT [FK_T_PEDIDO_T_ESTADO_PEDIDO]
    FOREIGN KEY ([ID_ESTADO_PEDIDO])
    REFERENCES [dbo].[T_ESTADO_PEDIDO]
        ([ID_ESTADO_PEDIDO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_PEDIDO_T_ESTADO_PEDIDO'
CREATE INDEX [IX_FK_T_PEDIDO_T_ESTADO_PEDIDO]
ON [dbo].[T_PEDIDO]
    ([ID_ESTADO_PEDIDO]);
GO

-- Creating foreign key on [ID_PEDIDO] in table 'T_ITEM_PEDIDO'
ALTER TABLE [dbo].[T_ITEM_PEDIDO]
ADD CONSTRAINT [FK_T_ITEM_PEDIDO_T_PEDIDO]
    FOREIGN KEY ([ID_PEDIDO])
    REFERENCES [dbo].[T_PEDIDO]
        ([ID_PEDIDO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_ITEM_PEDIDO_T_PEDIDO'
CREATE INDEX [IX_FK_T_ITEM_PEDIDO_T_PEDIDO]
ON [dbo].[T_ITEM_PEDIDO]
    ([ID_PEDIDO]);
GO

-- Creating foreign key on [ID_USUARIO_RESPONSAVEL] in table 'T_PEDIDO'
ALTER TABLE [dbo].[T_PEDIDO]
ADD CONSTRAINT [FK_T_PEDIDO_T_USUARIO]
    FOREIGN KEY ([ID_USUARIO_RESPONSAVEL])
    REFERENCES [dbo].[T_USUARIO]
        ([ID_USUARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_PEDIDO_T_USUARIO'
CREATE INDEX [IX_FK_T_PEDIDO_T_USUARIO]
ON [dbo].[T_PEDIDO]
    ([ID_USUARIO_RESPONSAVEL]);
GO

-- Creating foreign key on [ID_ESTADO_PEDIDO_ANTERIOR] in table 'T_ESTADO_PEDIDO'
ALTER TABLE [dbo].[T_ESTADO_PEDIDO]
ADD CONSTRAINT [FK_T_ESTADO_PEDIDO_T_ESTADO_PEDIDO]
    FOREIGN KEY ([ID_ESTADO_PEDIDO_ANTERIOR])
    REFERENCES [dbo].[T_ESTADO_PEDIDO]
        ([ID_ESTADO_PEDIDO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_ESTADO_PEDIDO_T_ESTADO_PEDIDO'
CREATE INDEX [IX_FK_T_ESTADO_PEDIDO_T_ESTADO_PEDIDO]
ON [dbo].[T_ESTADO_PEDIDO]
    ([ID_ESTADO_PEDIDO_ANTERIOR]);
GO

-- Creating foreign key on [ID_ESTADO_PEDIDO_SUCESSOR] in table 'T_ESTADO_PEDIDO'
ALTER TABLE [dbo].[T_ESTADO_PEDIDO]
ADD CONSTRAINT [FK_T_ESTADO_PEDIDO_T_ESTADO_PEDIDO1]
    FOREIGN KEY ([ID_ESTADO_PEDIDO_SUCESSOR])
    REFERENCES [dbo].[T_ESTADO_PEDIDO]
        ([ID_ESTADO_PEDIDO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_ESTADO_PEDIDO_T_ESTADO_PEDIDO1'
CREATE INDEX [IX_FK_T_ESTADO_PEDIDO_T_ESTADO_PEDIDO1]
ON [dbo].[T_ESTADO_PEDIDO]
    ([ID_ESTADO_PEDIDO_SUCESSOR]);
GO

-- Creating foreign key on [ID_UNIDADE_MEDIDA] in table 'T_ITEM'
ALTER TABLE [dbo].[T_ITEM]
ADD CONSTRAINT [FK_T_ITEM_T_UNIDADE_MEDIDA]
    FOREIGN KEY ([ID_UNIDADE_MEDIDA])
    REFERENCES [dbo].[T_UNIDADE_MEDIDA]
        ([ID_UNIDADE_MEDIDA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_ITEM_T_UNIDADE_MEDIDA'
CREATE INDEX [IX_FK_T_ITEM_T_UNIDADE_MEDIDA]
ON [dbo].[T_ITEM]
    ([ID_UNIDADE_MEDIDA]);
GO

-- Creating foreign key on [ID_UNIDADE_MEDIDA] in table 'T_ITEM_PEDIDO'
ALTER TABLE [dbo].[T_ITEM_PEDIDO]
ADD CONSTRAINT [FK_T_ITEM_PEDIDO_T_UNIDADE_MEDIDA]
    FOREIGN KEY ([ID_UNIDADE_MEDIDA])
    REFERENCES [dbo].[T_UNIDADE_MEDIDA]
        ([ID_UNIDADE_MEDIDA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_ITEM_PEDIDO_T_UNIDADE_MEDIDA'
CREATE INDEX [IX_FK_T_ITEM_PEDIDO_T_UNIDADE_MEDIDA]
ON [dbo].[T_ITEM_PEDIDO]
    ([ID_UNIDADE_MEDIDA]);
GO

-- Creating foreign key on [ID_PRODUTO] in table 'T_PRODUTO_UNIDADE_MEDIDA'
ALTER TABLE [dbo].[T_PRODUTO_UNIDADE_MEDIDA]
ADD CONSTRAINT [FK_T_PRODUTO_UNIDADE_MEDIDA_T_PRODUTO]
    FOREIGN KEY ([ID_PRODUTO])
    REFERENCES [dbo].[T_PRODUTO]
        ([ID_PRODUTO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_PRODUTO_UNIDADE_MEDIDA_T_PRODUTO'
CREATE INDEX [IX_FK_T_PRODUTO_UNIDADE_MEDIDA_T_PRODUTO]
ON [dbo].[T_PRODUTO_UNIDADE_MEDIDA]
    ([ID_PRODUTO]);
GO

-- Creating foreign key on [ID_UNIDADE_MEDIDA] in table 'T_PRODUTO_UNIDADE_MEDIDA'
ALTER TABLE [dbo].[T_PRODUTO_UNIDADE_MEDIDA]
ADD CONSTRAINT [FK_T_PRODUTO_UNIDADE_MEDIDA_T_UNIDADE_MEDIDA]
    FOREIGN KEY ([ID_UNIDADE_MEDIDA])
    REFERENCES [dbo].[T_UNIDADE_MEDIDA]
        ([ID_UNIDADE_MEDIDA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;

-- Creating non-clustered index for FOREIGN KEY 'FK_T_PRODUTO_UNIDADE_MEDIDA_T_UNIDADE_MEDIDA'
CREATE INDEX [IX_FK_T_PRODUTO_UNIDADE_MEDIDA_T_UNIDADE_MEDIDA]
ON [dbo].[T_PRODUTO_UNIDADE_MEDIDA]
    ([ID_UNIDADE_MEDIDA]);
GO

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------