//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrasilDidaticos.Servico {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servico.IBrasilDidaticos")]
    public interface IBrasilDidaticos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/TestarServico", ReplyAction="http://tempuri.org/IBrasilDidaticos/TestarServicoResponse")]
        string TestarServico(string NomeHost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/UsuarioLogar", ReplyAction="http://tempuri.org/IBrasilDidaticos/UsuarioLogarResponse")]
        BrasilDidaticos.Contrato.RetornoUsuario UsuarioLogar(BrasilDidaticos.Contrato.EntradaUsuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/UsuarioListar", ReplyAction="http://tempuri.org/IBrasilDidaticos/UsuarioListarResponse")]
        BrasilDidaticos.Contrato.RetornoUsuario UsuarioListar(BrasilDidaticos.Contrato.EntradaUsuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/UsuarioSalvar", ReplyAction="http://tempuri.org/IBrasilDidaticos/UsuarioSalvarResponse")]
        BrasilDidaticos.Contrato.RetornoUsuario UsuarioSalvar(BrasilDidaticos.Contrato.EntradaUsuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/SessaoExcluir", ReplyAction="http://tempuri.org/IBrasilDidaticos/SessaoExcluirResponse")]
        BrasilDidaticos.Contrato.RetornoSessao SessaoExcluir(BrasilDidaticos.Contrato.Sessao Sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/SessaoListar", ReplyAction="http://tempuri.org/IBrasilDidaticos/SessaoListarResponse")]
        BrasilDidaticos.Contrato.RetornoSessao SessaoListar(BrasilDidaticos.Contrato.Sessao Sessao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/PerfilListar", ReplyAction="http://tempuri.org/IBrasilDidaticos/PerfilListarResponse")]
        BrasilDidaticos.Contrato.RetornoPerfil PerfilListar(BrasilDidaticos.Contrato.EntradaPerfil Perfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/PerfilSalvar", ReplyAction="http://tempuri.org/IBrasilDidaticos/PerfilSalvarResponse")]
        BrasilDidaticos.Contrato.RetornoPerfil PerfilSalvar(BrasilDidaticos.Contrato.EntradaPerfil Perfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/PermissaoListar", ReplyAction="http://tempuri.org/IBrasilDidaticos/PermissaoListarResponse")]
        BrasilDidaticos.Contrato.RetornoPermissao PermissaoListar(BrasilDidaticos.Contrato.EntradaPermissao Permissao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/TaxaListar", ReplyAction="http://tempuri.org/IBrasilDidaticos/TaxaListarResponse")]
        BrasilDidaticos.Contrato.RetornoTaxa TaxaListar(BrasilDidaticos.Contrato.EntradaTaxa Taxa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/TaxaSalvar", ReplyAction="http://tempuri.org/IBrasilDidaticos/TaxaSalvarResponse")]
        BrasilDidaticos.Contrato.RetornoTaxa TaxaSalvar(BrasilDidaticos.Contrato.EntradaTaxa Taxa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/FornecedorBuscarCodigo", ReplyAction="http://tempuri.org/IBrasilDidaticos/FornecedorBuscarCodigoResponse")]
        string FornecedorBuscarCodigo(System.Guid IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/FornecedorListar", ReplyAction="http://tempuri.org/IBrasilDidaticos/FornecedorListarResponse")]
        BrasilDidaticos.Contrato.RetornoFornecedor FornecedorListar(BrasilDidaticos.Contrato.EntradaFornecedor Fornecedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/FornecedorSalvar", ReplyAction="http://tempuri.org/IBrasilDidaticos/FornecedorSalvarResponse")]
        BrasilDidaticos.Contrato.RetornoFornecedor FornecedorSalvar(BrasilDidaticos.Contrato.EntradaFornecedor Fornecedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/ProdutoBuscarCodigo", ReplyAction="http://tempuri.org/IBrasilDidaticos/ProdutoBuscarCodigoResponse")]
        string ProdutoBuscarCodigo(System.Guid IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/ProdutoListar", ReplyAction="http://tempuri.org/IBrasilDidaticos/ProdutoListarResponse")]
        BrasilDidaticos.Contrato.RetornoProduto ProdutoListar(BrasilDidaticos.Contrato.EntradaProduto Produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/ProdutoListarRelatorio", ReplyAction="http://tempuri.org/IBrasilDidaticos/ProdutoListarRelatorioResponse")]
        BrasilDidaticos.Contrato.RetornoProduto ProdutoListarRelatorio(BrasilDidaticos.Contrato.EntradaProduto Produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/ProdutoSalvar", ReplyAction="http://tempuri.org/IBrasilDidaticos/ProdutoSalvarResponse")]
        BrasilDidaticos.Contrato.RetornoProduto ProdutoSalvar(BrasilDidaticos.Contrato.EntradaProduto Produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/ProdutosSalvar", ReplyAction="http://tempuri.org/IBrasilDidaticos/ProdutosSalvarResponse")]
        BrasilDidaticos.Contrato.RetornoProduto ProdutosSalvar(BrasilDidaticos.Contrato.EntradaProdutos Produtos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/ParametroListar", ReplyAction="http://tempuri.org/IBrasilDidaticos/ParametroListarResponse")]
        BrasilDidaticos.Contrato.RetornoParametro ParametroListar(BrasilDidaticos.Contrato.EntradaParametro Parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/ParametrosSalvar", ReplyAction="http://tempuri.org/IBrasilDidaticos/ParametrosSalvarResponse")]
        BrasilDidaticos.Contrato.RetornoParametro ParametrosSalvar(BrasilDidaticos.Contrato.EntradaParametros Parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/ClienteBuscarCodigo", ReplyAction="http://tempuri.org/IBrasilDidaticos/ClienteBuscarCodigoResponse")]
        string ClienteBuscarCodigo(System.Guid IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/ClienteListar", ReplyAction="http://tempuri.org/IBrasilDidaticos/ClienteListarResponse")]
        BrasilDidaticos.Contrato.RetornoCliente ClienteListar(BrasilDidaticos.Contrato.EntradaCliente Cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/ClienteSalvar", ReplyAction="http://tempuri.org/IBrasilDidaticos/ClienteSalvarResponse")]
        BrasilDidaticos.Contrato.RetornoCliente ClienteSalvar(BrasilDidaticos.Contrato.EntradaCliente Cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/OrcamentoBuscarCodigo", ReplyAction="http://tempuri.org/IBrasilDidaticos/OrcamentoBuscarCodigoResponse")]
        string OrcamentoBuscarCodigo(System.Guid IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/EstadoOrcamentoListar", ReplyAction="http://tempuri.org/IBrasilDidaticos/EstadoOrcamentoListarResponse")]
        BrasilDidaticos.Contrato.RetornoEstadoOrcamento EstadoOrcamentoListar(BrasilDidaticos.Contrato.EntradaEstadoOrcamento EstadoOrcamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/OrcamentoListar", ReplyAction="http://tempuri.org/IBrasilDidaticos/OrcamentoListarResponse")]
        BrasilDidaticos.Contrato.RetornoOrcamento OrcamentoListar(BrasilDidaticos.Contrato.EntradaOrcamento Orcamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/OrcamentoSalvar", ReplyAction="http://tempuri.org/IBrasilDidaticos/OrcamentoSalvarResponse")]
        BrasilDidaticos.Contrato.RetornoOrcamento OrcamentoSalvar(BrasilDidaticos.Contrato.EntradaOrcamento Orcamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/UnidadeMedidaListar", ReplyAction="http://tempuri.org/IBrasilDidaticos/UnidadeMedidaListarResponse")]
        BrasilDidaticos.Contrato.RetornoUnidadeMedida UnidadeMedidaListar(BrasilDidaticos.Contrato.EntradaUnidadeMedida UnidadeMedida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/UnidadeMedidaSalvar", ReplyAction="http://tempuri.org/IBrasilDidaticos/UnidadeMedidaSalvarResponse")]
        BrasilDidaticos.Contrato.RetornoUnidadeMedida UnidadeMedidaSalvar(BrasilDidaticos.Contrato.EntradaUnidadeMedida UnidadeMedida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/PedidoBuscarCodigo", ReplyAction="http://tempuri.org/IBrasilDidaticos/PedidoBuscarCodigoResponse")]
        string PedidoBuscarCodigo(System.Guid IdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/PedidoListar", ReplyAction="http://tempuri.org/IBrasilDidaticos/PedidoListarResponse")]
        BrasilDidaticos.Contrato.RetornoPedido PedidoListar(BrasilDidaticos.Contrato.EntradaPedido Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/PedidoSalvar", ReplyAction="http://tempuri.org/IBrasilDidaticos/PedidoSalvarResponse")]
        BrasilDidaticos.Contrato.RetornoPedido PedidoSalvar(BrasilDidaticos.Contrato.EntradaPedido Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/EstadoPedidoListar", ReplyAction="http://tempuri.org/IBrasilDidaticos/EstadoPedidoListarResponse")]
        BrasilDidaticos.Contrato.RetornoEstadoPedido EstadoPedidoListar(BrasilDidaticos.Contrato.EntradaEstadoPedido EstadoPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/EmpresaListar", ReplyAction="http://tempuri.org/IBrasilDidaticos/EmpresaListarResponse")]
        BrasilDidaticos.Contrato.RetornoEmpresa EmpresaListar(BrasilDidaticos.Contrato.EntradaEmpresa Empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrasilDidaticos/UnidadeFederativaListar", ReplyAction="http://tempuri.org/IBrasilDidaticos/UnidadeFederativaListarResponse")]
        BrasilDidaticos.Contrato.RetornoUnidadeFederativa UnidadeFederativaListar();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBrasilDidaticosChannel : BrasilDidaticos.Servico.IBrasilDidaticos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrasilDidaticosClient : System.ServiceModel.ClientBase<BrasilDidaticos.Servico.IBrasilDidaticos>, BrasilDidaticos.Servico.IBrasilDidaticos {
        
        public BrasilDidaticosClient() {
        }
        
        public BrasilDidaticosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrasilDidaticosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrasilDidaticosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrasilDidaticosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestarServico(string NomeHost) {
            return base.Channel.TestarServico(NomeHost);
        }
        
        public BrasilDidaticos.Contrato.RetornoUsuario UsuarioLogar(BrasilDidaticos.Contrato.EntradaUsuario Usuario) {
            return base.Channel.UsuarioLogar(Usuario);
        }
        
        public BrasilDidaticos.Contrato.RetornoUsuario UsuarioListar(BrasilDidaticos.Contrato.EntradaUsuario Usuario) {
            return base.Channel.UsuarioListar(Usuario);
        }
        
        public BrasilDidaticos.Contrato.RetornoUsuario UsuarioSalvar(BrasilDidaticos.Contrato.EntradaUsuario Usuario) {
            return base.Channel.UsuarioSalvar(Usuario);
        }
        
        public BrasilDidaticos.Contrato.RetornoSessao SessaoExcluir(BrasilDidaticos.Contrato.Sessao Sessao) {
            return base.Channel.SessaoExcluir(Sessao);
        }
        
        public BrasilDidaticos.Contrato.RetornoSessao SessaoListar(BrasilDidaticos.Contrato.Sessao Sessao) {
            return base.Channel.SessaoListar(Sessao);
        }
        
        public BrasilDidaticos.Contrato.RetornoPerfil PerfilListar(BrasilDidaticos.Contrato.EntradaPerfil Perfil) {
            return base.Channel.PerfilListar(Perfil);
        }
        
        public BrasilDidaticos.Contrato.RetornoPerfil PerfilSalvar(BrasilDidaticos.Contrato.EntradaPerfil Perfil) {
            return base.Channel.PerfilSalvar(Perfil);
        }
        
        public BrasilDidaticos.Contrato.RetornoPermissao PermissaoListar(BrasilDidaticos.Contrato.EntradaPermissao Permissao) {
            return base.Channel.PermissaoListar(Permissao);
        }
        
        public BrasilDidaticos.Contrato.RetornoTaxa TaxaListar(BrasilDidaticos.Contrato.EntradaTaxa Taxa) {
            return base.Channel.TaxaListar(Taxa);
        }
        
        public BrasilDidaticos.Contrato.RetornoTaxa TaxaSalvar(BrasilDidaticos.Contrato.EntradaTaxa Taxa) {
            return base.Channel.TaxaSalvar(Taxa);
        }
        
        public string FornecedorBuscarCodigo(System.Guid IdEmpresa) {
            return base.Channel.FornecedorBuscarCodigo(IdEmpresa);
        }
        
        public BrasilDidaticos.Contrato.RetornoFornecedor FornecedorListar(BrasilDidaticos.Contrato.EntradaFornecedor Fornecedor) {
            return base.Channel.FornecedorListar(Fornecedor);
        }
        
        public BrasilDidaticos.Contrato.RetornoFornecedor FornecedorSalvar(BrasilDidaticos.Contrato.EntradaFornecedor Fornecedor) {
            return base.Channel.FornecedorSalvar(Fornecedor);
        }
        
        public string ProdutoBuscarCodigo(System.Guid IdEmpresa) {
            return base.Channel.ProdutoBuscarCodigo(IdEmpresa);
        }
        
        public BrasilDidaticos.Contrato.RetornoProduto ProdutoListar(BrasilDidaticos.Contrato.EntradaProduto Produto) {
            return base.Channel.ProdutoListar(Produto);
        }
        
        public BrasilDidaticos.Contrato.RetornoProduto ProdutoListarRelatorio(BrasilDidaticos.Contrato.EntradaProduto Produto) {
            return base.Channel.ProdutoListarRelatorio(Produto);
        }
        
        public BrasilDidaticos.Contrato.RetornoProduto ProdutoSalvar(BrasilDidaticos.Contrato.EntradaProduto Produto) {
            return base.Channel.ProdutoSalvar(Produto);
        }
        
        public BrasilDidaticos.Contrato.RetornoProduto ProdutosSalvar(BrasilDidaticos.Contrato.EntradaProdutos Produtos) {
            return base.Channel.ProdutosSalvar(Produtos);
        }
        
        public BrasilDidaticos.Contrato.RetornoParametro ParametroListar(BrasilDidaticos.Contrato.EntradaParametro Parametro) {
            return base.Channel.ParametroListar(Parametro);
        }
        
        public BrasilDidaticos.Contrato.RetornoParametro ParametrosSalvar(BrasilDidaticos.Contrato.EntradaParametros Parametros) {
            return base.Channel.ParametrosSalvar(Parametros);
        }
        
        public string ClienteBuscarCodigo(System.Guid IdEmpresa) {
            return base.Channel.ClienteBuscarCodigo(IdEmpresa);
        }
        
        public BrasilDidaticos.Contrato.RetornoCliente ClienteListar(BrasilDidaticos.Contrato.EntradaCliente Cliente) {
            return base.Channel.ClienteListar(Cliente);
        }
        
        public BrasilDidaticos.Contrato.RetornoCliente ClienteSalvar(BrasilDidaticos.Contrato.EntradaCliente Cliente) {
            return base.Channel.ClienteSalvar(Cliente);
        }
        
        public string OrcamentoBuscarCodigo(System.Guid IdEmpresa) {
            return base.Channel.OrcamentoBuscarCodigo(IdEmpresa);
        }
        
        public BrasilDidaticos.Contrato.RetornoEstadoOrcamento EstadoOrcamentoListar(BrasilDidaticos.Contrato.EntradaEstadoOrcamento EstadoOrcamento) {
            return base.Channel.EstadoOrcamentoListar(EstadoOrcamento);
        }
        
        public BrasilDidaticos.Contrato.RetornoOrcamento OrcamentoListar(BrasilDidaticos.Contrato.EntradaOrcamento Orcamento) {
            return base.Channel.OrcamentoListar(Orcamento);
        }
        
        public BrasilDidaticos.Contrato.RetornoOrcamento OrcamentoSalvar(BrasilDidaticos.Contrato.EntradaOrcamento Orcamento) {
            return base.Channel.OrcamentoSalvar(Orcamento);
        }
        
        public BrasilDidaticos.Contrato.RetornoUnidadeMedida UnidadeMedidaListar(BrasilDidaticos.Contrato.EntradaUnidadeMedida UnidadeMedida) {
            return base.Channel.UnidadeMedidaListar(UnidadeMedida);
        }
        
        public BrasilDidaticos.Contrato.RetornoUnidadeMedida UnidadeMedidaSalvar(BrasilDidaticos.Contrato.EntradaUnidadeMedida UnidadeMedida) {
            return base.Channel.UnidadeMedidaSalvar(UnidadeMedida);
        }
        
        public string PedidoBuscarCodigo(System.Guid IdEmpresa) {
            return base.Channel.PedidoBuscarCodigo(IdEmpresa);
        }
        
        public BrasilDidaticos.Contrato.RetornoPedido PedidoListar(BrasilDidaticos.Contrato.EntradaPedido Pedido) {
            return base.Channel.PedidoListar(Pedido);
        }
        
        public BrasilDidaticos.Contrato.RetornoPedido PedidoSalvar(BrasilDidaticos.Contrato.EntradaPedido Pedido) {
            return base.Channel.PedidoSalvar(Pedido);
        }
        
        public BrasilDidaticos.Contrato.RetornoEstadoPedido EstadoPedidoListar(BrasilDidaticos.Contrato.EntradaEstadoPedido EstadoPedido) {
            return base.Channel.EstadoPedidoListar(EstadoPedido);
        }
        
        public BrasilDidaticos.Contrato.RetornoEmpresa EmpresaListar(BrasilDidaticos.Contrato.EntradaEmpresa Empresa) {
            return base.Channel.EmpresaListar(Empresa);
        }
        
        public BrasilDidaticos.Contrato.RetornoUnidadeFederativa UnidadeFederativaListar() {
            return base.Channel.UnidadeFederativaListar();
        }
    }
}
